### ISSUE TITLE
Directory of tabledata is working directory by default

### ISSUE THREAD

**Issue by hover2pi** [BDNYC/astrodbkit#87]
When the .sql tables are saved in the `tabledata` directory, it defaults to the working directory. It should be the same directory as the .db file. 

```
- database.db
- database.sql
- tabledata
---- sources.sql
---- spectra.sql
```

And rather than have the same `directory` argument in `__init__`, `save`, and `close` methods, we should declare a `directory` attribute when the instance is created.

**Comment by dr-rodriguez** [comment]
I agree; these would be useful changes.

**Comment by hover2pi** [comment]
Ok, I replaced the `directory` arguments with `self.directory` (0991a57)

**Comment by dr-rodriguez** [comment]
Should have done a pull request, or placed it on a branch. This change does not pass our tests.

Also, this new version makes it sound like the db file is always regenerated since it's outside the IF statement? I feel that's bad practice since you may be given just a db file and not have the tabledata directory yet.

**Comment by dr-rodriguez** [comment]
I've gone ahead and created a branch **directory_change** and moved these changes to it. The **master** branch remains mostly unchanged and working. Once we get this working, we can merge it back to **master**.

**Comment by dr-rodriguez** [comment]
Issues fixed, travis runs with no errors now. Branch merged back to **master**
